# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "significance"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["caleon"]
  s.date = "2012-10-25"
  s.description = "    Similar in behavior to Object#presence defined in ActiveSupport,\n    Significance is a state which determines not just the blank-ness of an\n    object but whether or not the non-blank object has any real-world value.\n    The utility of this gem can best be demonstrated when considering the\n    merging of two hashes. Under normal circumstances the mere existence of an\n    equivalent key in the second hash results in its overriding the\n    corresponding value in the original hash. Using Hash#significant_merge,\n    however, the second hash will retain only key-value pairs whose values are\n    \"significant,\" even applying the significance filter recursively into child\n    hashes or arrays.\n"
  s.email = "caleon@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/significance.rb",
    "lib/significance/core_ext.rb",
    "lib/significance/core_ext/array.rb",
    "lib/significance/core_ext/false_class.rb",
    "lib/significance/core_ext/hash.rb",
    "lib/significance/core_ext/object.rb",
    "lib/significance/core_ext/set.rb",
    "lib/significance/core_ext/string.rb",
    "lib/tasks/significance_tasks.rake",
    "significance.gemspec",
    "spec/significance_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/caleon/significance"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Similar in behavior to Object#presence defined in ActiveSupport, Significance is a state which determines not just the blank-ness of an object but whether or not the non-blank object has any real-world value."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

